### ISSUE TITLE
1.4.1: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [datadriventests/ddt#88]
```
+ cd ddt-1.4.1
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-ddt-1.4.1-2.fc33.x86_64/usr/lib/python3.8/site-packages
+ nosetests --verbose
test_dicts_extracted_into_kwargs_1 (test.test_example.FooTestCase) ... ok
test_dicts_extracted_into_kwargs_2 (test.test_example.FooTestCase) ... ok
Missing args with value {0} and {1} ... ok
Missing args with value {0} and {1} ... ok
Missing args with value {0} and {1} ... ok
Missing args with value {0} and {1} ... ok
Missing kargs with value {value} {value2} ... ok
Missing kargs with value {value} {value2} ... ok
Missing kargs with value {value} {value2} ... ok
Missing kargs with value {value} {value2} ... ok
test_file_data_json_dict_1_unsorted_list ... ok
test_file_data_json_dict_2_sorted_list ... ok
test_file_data_json_dict_dict_1_positive_integer_range ... ok
test_file_data_json_dict_dict_2_negative_integer_range ... ok
test_file_data_json_dict_dict_3_positive_real_range ... ok
test_file_data_json_dict_dict_4_negative_real_range ... ok
test_file_data_json_list_1_Hello ... ok
test_file_data_json_list_2_Goodbye ... ok
test_file_data_yaml_dict_1_unsorted_list ... ok
test_file_data_yaml_dict_2_sorted_list ... ok
test_file_data_yaml_dict_dict_1_positive_integer_range ... ok
test_file_data_yaml_dict_dict_2_negative_integer_range ... ok
test_file_data_yaml_dict_dict_3_positive_real_range ... ok
test_file_data_yaml_dict_dict_4_negative_real_range ... ok
test_file_data_yaml_list_1_Hello ... ok
test_file_data_yaml_list_2_Goodbye ... ok
test_greater_1_test_2_greater_than_1 (test.test_example.FooTestCase) ... ok
test_greater_2_test_10_greater_than_5 (test.test_example.FooTestCase) ... ok
Test docstring 1 ... ok
Test docstring 2 ... ok
test_larger_than_two_1_3 (test.test_example.FooTestCase) ... ok
test_larger_than_two_2_4 (test.test_example.FooTestCase) ... ok
test_larger_than_two_3_12 (test.test_example.FooTestCase) ... ok
test_larger_than_two_4_23 (test.test_example.FooTestCase) ... ok
Larger than two with value 3 ... ok
Larger than two with value 4 ... ok
Larger than two with value 12 ... ok
Larger than two with value 23 ... ok
test_list_extracted_into_arguments_1__3__2_ (test.test_example.FooTestCase) ... ok
test_list_extracted_into_arguments_2__4__3_ (test.test_example.FooTestCase) ... ok
test_list_extracted_into_arguments_3__5__3_ (test.test_example.FooTestCase) ... ok
Extract into args with first value 3 and second value 2 ... ok
Extract into args with first value 4 and second value 3 ... ok
Extract into args with first value 5 and second value 3 ... ok
test_not_larger_than_two_1_1 (test.test_example.FooTestCase) ... ok
test_not_larger_than_two_2__3 (test.test_example.FooTestCase) ... ok
test_not_larger_than_two_3_2 (test.test_example.FooTestCase) ... ok
test_not_larger_than_two_4_0 (test.test_example.FooTestCase) ... ok
test_tuples_extracted_into_arguments_1__3__2_ (test.test_example.FooTestCase) ... ok
test_tuples_extracted_into_arguments_2__4__3_ (test.test_example.FooTestCase) ... ok
test_tuples_extracted_into_arguments_3__5__3_ (test.test_example.FooTestCase) ... ok
test_undecorated (test.test_example.FooTestCase) ... ok
test_unicode_1_ascii (test.test_example.FooTestCase) ... ok
test_unicode_2_non_ascii__ (test.test_example.FooTestCase) ... ok
test_custom_yaml_loader_10_python_float ... ok
test_custom_yaml_loader_1_bool ... ok
test_custom_yaml_loader_2_str ... ok
test_custom_yaml_loader_3_int ... ok
test_custom_yaml_loader_4_float ... ok
test_custom_yaml_loader_5_python_list ... ok
test_custom_yaml_loader_6_python_dict ... ok
test_custom_yaml_loader_7_my_class ... ok
test_custom_yaml_loader_8_python_str ... ok
test_custom_yaml_loader_9_python_int ... ok
Failure: TypeError (Cannot extend enumerations) ... ERROR
Test the ``data`` method decorator ... ok
Test the ``file_data`` method decorator ... ok
Test the ``ddt`` class decorator ... ok
Test the ``ddt`` class decorator with ``INDEX_ONLY`` test name format ... ok
Test the ``ddt`` class decorator with ``DEFAULT`` test name format ... ok
Test that the ``file_data`` decorator creates two tests ... ok
Test that ``file_data`` creates tests with the correct name ... ok
Test that data is fed to the decorated tests ... ok
Test that data is fed to the decorated tests from a file ... ok
Test that a ValueError is raised when JSON file is missing ... ok
Test that a ValueError is raised when YAML file is missing ... ok
Test the ``__name__`` attribute handling of ``data`` items with ``ddt`` ... ok
Test the ``__doc__`` attribute handling of ``data`` items with ``ddt`` ... ok
Test that unicode strings are converted to function names correctly ... ok
Test not using value if non-trivial arguments ... ok
Test that data is fed to the decorated tests ... ok
Test that YAML files containing python tags throw no exception if an ... ok
Test that YAML files are not loaded if YAML is not installed. ... ok

======================================================================
ERROR: Failure: TypeError (Cannot extend enumerations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.8/site-packages/nose/loader.py", line 522, in makeTest
    return self._makeTest(obj, parent)
  File "/usr/lib/python3.8/site-packages/nose/loader.py", line 567, in _makeTest
    obj = transplant_class(obj, parent.__name__)
  File "/usr/lib/python3.8/site-packages/nose/util.py", line 642, in transplant_class
    class C(cls):
  File "/usr/lib64/python3.8/enum.py", line 124, in __prepare__
    member_type, first_enum = metacls._get_mixins_(bases)
  File "/usr/lib64/python3.8/enum.py", line 502, in _get_mixins_
    raise TypeError("Cannot extend enumerations")
TypeError: Cannot extend enumerations

----------------------------------------------------------------------
Ran 83 tests in 0.122s

FAILED (errors=1)
error: Bad exit status from /var/tmp/rpm-tmp.Doogsq (%check)
```

**Comment by wswld** [comment]
We no longer run test suite with nose, but switched to `pytest`. Nose is officially deprecated package. Both `pytest` and `unittest` run fine.

**Comment by kloczek** [comment]
OK pytest is working.

Thx. Closing
